# Generated by Django 5.1.5 on 2026-04-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roll_no', models.CharField(max_length=50, unique=True)),
                ('contact_no', models.CharField(max_length=15)),
                ('verticals', models.JSONField()),
            ],
        ),
    ]
