# Generated by Django 5.1.5 on 2026-04-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_coordinators'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerscore',
            name='last_game_start',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
